# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sablier-flow
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
contracts:
  - name: FlowV10
    handler: src/mappings/index.ts
    events:
      - event: AdjustFlowStream(uint256 indexed streamId, uint256 totalDebt, uint128 oldRatePerSecond, uint128 newRatePerSecond)
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CreateFlowStream(uint256 streamId, address indexed sender, address indexed recipient, uint128 ratePerSecond, address indexed token,
          bool transferable)
      - event: DepositFlowStream(uint256 indexed streamId, address indexed funder, uint128 amount)
      - event: PauseFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint256 totalDebt)
      - event: RefundFromFlowStream(uint256 indexed streamId, address indexed sender, uint128 amount)
      - event: RestartFlowStream(uint256 indexed streamId, address indexed sender, uint128 ratePerSecond)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event: 
          VoidFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, address caller, uint256 newTotalDebt,
          uint256 writtenOffDebt)
      - event: 
          WithdrawFromFlowStream( uint256 indexed streamId, address indexed to, address indexed token, address caller, uint128 withdrawAmount,
          uint128 protocolFeeAmount)
networks:
  - id: 42161
    start_block: 161026550
    contracts:
      - name: FlowV10
        address:
          - 0x18a12a7035aa56240bcd236bc019aa245dcc015a
  - id: 43114
    start_block: 41023950
    contracts:
      - name: FlowV10
        address:
          - 0x8c172e42c06302e3cfe555dc4d6b71a756ee186b
  - id: 8453
    start_block: 8026890
    contracts:
      - name: FlowV10
        address:
          - 0x1a9adc0e2114c8407cc31669baafeee031d15dd2
  - id: 84532
    start_block: 12641000
    contracts:
      - name: FlowV10
        address:
          - 0xd5f78708d83ac2bc8734a8cdf2d112c1bb3b62a2
  - id: 81457
    start_block: 244700
    contracts:
      - name: FlowV10
        address:
          - 0xfdac2799644141856e20e021ac06f231cafc731f
  - id: 56
    start_block: 34438430
    contracts:
      - name: FlowV10
        address:
          - 0xfce01f79247cf450062545e7155d7bd568551d0e
  - id: 100
    start_block: 31491790
    contracts:
      - name: FlowV10
        address:
          - 0x5515f774a4db42820802333ba575f68a6e85bd13
  - id: 59144
    start_block: 7728000
    contracts:
      - name: FlowV10
        address:
          - 0x949bfa08f1632432a2656a9db17ca34d54da8296
  - id: 1
    start_block: 17615650
    contracts:
      - name: FlowV10
        address:
          - 0x2d9221a63e12aa796619cb381ec4a71b201281f5
  - id: 34443
    start_block: 11343000
    hypersync_config:
      url: https://mode.hypersync.xyz
    contracts:
      - name: FlowV10
        address:
          - 0x75970dde488431fc4961494569def3269f20d6b3
  - id: 2818
    start_block: 45000
    hypersync_config:
      url: https://morph.hypersync.xyz/
    contracts:
      - name: FlowV10
        address:
          - 0xfe6972d0ae797fae343e5a58d0c7d8513937f092
  - id: 10
    start_block: 113621900
    contracts:
      - name: FlowV10
        address:
          - 0x906356e4e6410ea0a97dbc5b071cf394ab0dcd69
  - id: 137
    start_block: 51245830
    contracts:
      - name: FlowV10
        address:
          - 0xcf2d812d5aad4e6fec3b05850ff056b21159d496
  - id: 534352
    start_block: 1675330
    contracts:
      - name: FlowV10
        address:
          - 0x66826f53bffeaab71adc7fe1a77e86f8268848d8
  - id: 5330
    start_block: 2896400
    hypersync_config:
      url: https://extrabud.hypersync.xyz
    contracts:
      - name: FlowV10
        address:
          - 0x4f5f9b3fb57bba43aaf90e3f71d8f8f384e88e20
  - id: 5845
    start_block: 2516000
    hypersync_config:
      url: https://tangle.hypersync.xyz
    contracts:
      - name: FlowV10
        address:
          - 0xcff4a803b0bf55dd1be38fb96088478f3d2eecf2
  - id: 324
    start_block: 33148900
    contracts:
      - name: FlowV10
        address:
          - 0x015899a075b7c181e357cd0ed000683dbb4f1fce
  - id: 11155111
    start_block: 4904890
    contracts:
      - name: FlowV10
        address:
          - 0x83dd52fca44e069020b58155b761a590f12b59d3
