# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sablier-flow
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
contracts:
  - name: FlowV10
    handler: src/mappings/index.ts
    events:
      - event:
          AdjustFlowStream(uint256 indexed streamId, uint256 totalDebt, uint128 oldRatePerSecond, uint128
          newRatePerSecond)
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CreateFlowStream(uint256 streamId, address indexed sender, address indexed recipient, uint128 ratePerSecond,
          address indexed token, bool transferable)
      - event: DepositFlowStream(uint256 indexed streamId, address indexed funder, uint128 amount)
      - event:
          PauseFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint256
          totalDebt)
      - event: RefundFromFlowStream(uint256 indexed streamId, address indexed sender, uint128 amount)
      - event: RestartFlowStream(uint256 indexed streamId, address indexed sender, uint128 ratePerSecond)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event:
          VoidFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, address caller,
          uint256 newTotalDebt, uint256 writtenOffDebt)
      - event:
          WithdrawFromFlowStream( uint256 indexed streamId, address indexed to, address indexed token, address caller,
          uint128 withdrawAmount, uint128 protocolFeeAmount)
networks:
  - id: 11155111
    start_block: 4904890
    contracts:
      - name: FlowV10
        address:
          - 0x83dd52fca44e069020b58155b761a590f12b59d3
